[tool.poetry]

name = "memegen"
version = "9.0"
description = "The free and open source API to generate memes."
authors = ["Jace Browning <support@maketested.com>"]
license = "MIT"

packages = [{ include = "app" }]

[tool.poetry.dependencies]

python = "^3.9"

# Sanic
sanic = "~21.6.1"
sanic-cors = "^1.0"
sanic-openapi = "~21.3.2"
sanic-routing = { git = "https://github.com/sanic-org/sanic-routing", rev = "5501794506a8e8c730de904cd6dbd57d68e90757" }

# Markdown
markdown = "~3.2.2"
pymdown-extensions = "^8.0"
pygments = "^2.7.0"

# Images
pillow = "^8.3.1"
spongemock = "~0.3.4"

# Utilities
aiocache = "~0.11.1"
aiohttp = "^3.7.4"
aiopath = "~0.4.9"
datafiles = "~0.15"
furl = "^2.1.1"
minilog = "^2.0.1"

# Production
bugsnag = "^4.0.3"
gunicorn = "^20.1"
uvicorn = "~0.14"

[tool.poetry.dev-dependencies]

# Formatting
isort = "=5.5.1"
black = "=20.8b1"

# Type Checking
mypy = "~0.900"
autoflake = "^1.3.1"
types-pkg_resources = "*"
types-aiofiles = "*"
types-requests = "*"

# Testing
pytest = "^6.0"
pytest-asyncio = "*"
pytest-describe = { git = "https://github.com/pytest-dev/pytest-describe", rev = "9014bf3ee564518aad3622b5f035f7ca6139e398" }
pytest-expecter = "^2.1"
pytest-random = "*"
pytest-rerunfailures = "^9.1"
pytest-cov = "^2.7"
sanic-testing = "*"
locust = "^1.2.3"

# Coverage
coveragespace = "^4.2"

# Documentation
mkdocs = "^1.1"

# Utilities
honcho = { git = "https://github.com/nickstenning/honcho", rev = "b4de1aa0504d41c0f05efbb04f63c624fccded81" }
ipdb = "*"
rope = "^0.18.0"
watchdog = { version = "=0.10.3", extras = ["watchmedo"] }

[tool.black]

quiet = true

[tool.mypy]

ignore_missing_imports = true
no_implicit_optional = true
check_untyped_defs = true

plugins = "datafiles.plugins:mypy"

cache_dir = ".cache/mypy/"

[tool.pytest.ini_options]

testpaths = "app"

addopts = """
--no-header \
--random \
--show-capture=log \
--cov=app --cov-report=term-missing:skip-covered --cov-report=html:.cache/htmlcov --no-cov-on-fail
"""

cache_dir = ".cache"

markers = "slow"

[build-system]

requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
