name: Change My Mind
source: https://knowyourmeme.com/memes/steven-crowders-change-my-mind-campus-sign
text:
  - color: black
    style: upper
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 10.0
    scale_x: 0.3
    scale_y: 0.35
  - color: black
    style: upper
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.3
    scale_y: 0.35
  - color: black
    style: upper
    anchor_x: 0.4
    anchor_y: 0.4
    angle: 0.0
    scale_x: 0.3
    scale_y: 0.35
  - color: black
    style: upper
    anchor_x: 0.4
    anchor_y: 0.4
    angle: 45.0
    scale_x: 0.3
    scale_y: 0.35
styles:
  -
example:
  - pineapples don't belong on pizza
overlay:
  - center_x: 0.5
    center_y: 0.5
    scale: 0.25
